name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Download WeChat DevTools CLI
        run: |
          curl -L https://servicewechat.com/wxa-dev-logic/download_redirect?type=darwin_x64&from=mpwiki&download_version=1062312061&version_type=1 -o wechat_dev_tools.dmg
          hdiutil attach wechat_dev_tools.dmg
          cp -r /Volumes/WeChat\ DevTools/WeChat\ DevTools.app /Applications/
          hdiutil detach /Volumes/WeChat\ DevTools/
          sudo ln -s /Applications/WeChat\ DevTools.app/Contents/MacOS/cli /usr/local/bin/cli

      - name: Run Tests
        env:
          CLI_PATH: /usr/local/bin/cli
        run: npm test
