name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install WeChat DevTools (CLI)
      run: |
        wget https://servicewechat.com/download/wechatwebdevtools/linux64/Stable/1.05.2209300.tar.gz -O wechat_dev_tools.tar.gz
        mkdir -p wechat_dev_tools
        tar -xzf wechat_dev_tools.tar.gz -C wechat_dev_tools
        sudo chmod +x wechat_dev_tools/cli

    - name: Set CLI_PATH environment variable
      run: echo "CLI_PATH=${{ github.workspace }}/wechat_dev_tools/cli" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
